---
# Implement your Post Workload deployment tasks here
- name: output workshop info
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
    - ""
    - "Camel - {{ lab_title }} provisioned for {{ num_users }} user(s)"
    - ""
    - "HOW TO GET STARTED:"
    - "Participants only need to register to get started!"
    - "They need to get a username. Provide the following registration URL (or create a short link easier to type in):"
    - "User Registration: https://users-registration.{{ route_subdomain }}"
    - "To register, they need to enter an email and the password below:"
    - "Registration password is '{{ user_access_token }}'"
    - ""
    - "To manage registrations (admins), use the link below:"
    - "Admin dashboard: https://users-registration.{{ route_subdomain }}/admin"
    - "Admin credentials: 'admin/{{ workshop_registration_admin_password }}'"
    - ""
    - "IMPORTANT:"
    - "Visit the workshop's home page in 'The Source', where you'll find all the details you need to run the workshop:"
    - "https://source.redhat.com/communities/communities_of_practice/applications/integration_cop/blogs/integration_articles/a_day_in_the_life_camel_workshop_on_rhpds"
    - "If you're missing information (e.g. tokens/credentials for labs), you'll find all the workshop details needed by following the link above, the home page of DIL Camel."
    - ""
    - "Solution Explorer: "
    - "https://tutorial-web-app-webapp.{{ route_subdomain }}"
    - ""
    - "OpenShift Console: {{ console_url }}"
    - "Cluster admin login with '{{ ocp_username }}' / 'r3dh4t1!'"
    - ""
  when: not silent|bool

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
