---

- name: Determine cluster wildcard domain
  kubernetes.core.k8s_info:
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
  register: r_ingress_controller

- name: Save cluster apps domain variable
  ansible.builtin.set_fact:
    _ocp4_workload_opentour_dach_2022_shared_apps_domain: "{{ r_ingress_controller.resources[0].status.domain }}"

- name: Set up cluster-configuratoin
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'apps/cluster-configuration.yaml.j2' ) | from_yaml }}"

- name: Rollout helm
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'appsets/generic.yaml.j2' ) | from_yaml }}"
  with_items:
    - service-mesh-app
    - service-mesh-system

# - name: Set up GitOps environment
#   when: ocp4_workload_opentour_dach_2022_shared_gitops_setup | bool
#   block:
#   - name: Create demo namespaces for all users
#     vars:
#       _ocp4_workload_opentour_dach_2022_shared_namespace: >-
#         {{ ocp4_workload_opentour_dach_2022_shared_demo_namespace_prefix }}{{
#            ocp4_workload_opentour_dach_2022_shared_gitea_user_prefix }}{{ n }}
#     kubernetes.core.k8s:
#       state: present
#       definition: "{{ lookup('template', 'apps/namespace.yaml.j2' ) | from_yaml }}"
#     loop: "{{ range(1, ocp4_workload_opentour_dach_2022_shared_gitea_user_count | int + 1) | list }}"
#     loop_control:
#       loop_var: n
#       label: "{{ ocp4_workload_opentour_dach_2022_shared_gitea_user_prefix }}{{ n }}"

#   - name: Create cicd namespaces for all users
#     vars:
#       _ocp4_workload_opentour_dach_2022_shared_namespace: >-
#         {{ ocp4_workload_opentour_dach_2022_shared_pipeline_namespace_prefix }}{{
#            ocp4_workload_opentour_dach_2022_shared_gitea_user_prefix }}{{ n }}
#     kubernetes.core.k8s:
#       state: present
#       definition: "{{ lookup('template', 'apps/namespace.yaml.j2' ) | from_yaml }}"
#     loop: "{{ range(1, ocp4_workload_opentour_dach_2022_shared_gitea_user_count | int + 1) | list }}"
#     loop_control:
#       loop_var: n
#       label: "{{ ocp4_workload_opentour_dach_2022_shared_gitea_user_prefix }}{{ n }}"

#   - name: Create ArgoCD and Tekton environment for all users
#     kubernetes.core.k8s:
#       state: present
#       definition: "{{ lookup('template', 'cicd/applicationset.yaml.j2' ) | from_yaml }}"

#   - name: Create PostgreSQL database 'orders' for all users
#     vars:
#       _ocp4_workload_opentour_dach_2022_shared_db_app_name: "{{ ocp4_workload_opentour_dach_2022_shared_orders_db_app_name }}"
#       _ocp4_workload_opentour_dach_2022_shared_db_name: "{{ ocp4_workload_opentour_dach_2022_shared_orders_db_name }}"
#       _ocp4_workload_opentour_dach_2022_shared_db_user: "{{ ocp4_workload_opentour_dach_2022_shared_orders_db_user }}"
#       _ocp4_workload_opentour_dach_2022_shared_db_password: "{{ ocp4_workload_opentour_dach_2022_shared_orders_db_password }}"
#     kubernetes.core.k8s:
#       state: present
#       definition: "{{ lookup('template', 'postgresql/applicationset.yaml.j2' ) | from_yaml }}"

#   - name: Create PostgreSQL database 'inventory' for all users
#     vars:
#       _ocp4_workload_opentour_dach_2022_shared_db_app_name: "{{ ocp4_workload_opentour_dach_2022_shared_inventory_db_app_name }}"
#       _ocp4_workload_opentour_dach_2022_shared_db_name: "{{ ocp4_workload_opentour_dach_2022_shared_inventory_db_name }}"
#       _ocp4_workload_opentour_dach_2022_shared_db_user: "{{ ocp4_workload_opentour_dach_2022_shared_inventory_db_user }}"
#       _ocp4_workload_opentour_dach_2022_shared_db_password: "{{ ocp4_workload_opentour_dach_2022_shared_inventory_db_password }}"
#     kubernetes.core.k8s:
#       state: present
#       definition: "{{ lookup('template', 'postgresql/applicationset.yaml.j2' ) | from_yaml }}"

#   # Don't use ApplicationSet -> users can change their applications
#   - name: Create ArgoCD Applications for all users
#     vars:
#       _ocp4_workload_opentour_dach_2022_shared_namespace: >-
#         {{ ocp4_workload_opentour_dach_2022_shared_demo_namespace_prefix }}{{
#            ocp4_workload_opentour_dach_2022_shared_gitea_user_prefix }}{{ n }}
#       _ocp4_workload_opentour_dach_2022_shared_user: "{{ ocp4_workload_opentour_dach_2022_shared_gitea_user_prefix }}{{ n }}"
#     kubernetes.core.k8s:
#       state: present
#       definition: "{{ lookup('template', 'apps/application.yaml.j2' ) | from_yaml }}"
#     loop: "{{ range(1, ocp4_workload_opentour_dach_2022_shared_gitea_user_count | int + 1) | list }}"
#     loop_control:
#       loop_var: n
#       label: "{{ ocp4_workload_opentour_dach_2022_shared_gitea_user_prefix }}{{ n }}"

# -------------------
# AgnosticD User Info
# -------------------
