---
- name: Generate SSH keys
  command: >-
    ssh-keygen -b 2048 -t rsa -q -N ""
    -f {{ vmc_ssh_key_path | quote }}
  args:
    creates: "{{ vmc_ssh_key_path }}"

- name: Set permission
  file:
    path: "{{ vmc_ssh_key_path }}"
    mode: 0400

- name: Generate SSH pub key
  shell: >-
    ssh-keygen -y -f {{ vmc_ssh_key_path | quote }}
    > {{ vmc_ssh_pub_key_path | quote }}
  args:
    creates: "{{ vmc_ssh_pub_key_path }}"

- name: Set permission
  file:
    path: "{{ vmc_ssh_pub_key_path }}"
    mode: 0400

- name: Save key for ssh config
  set_fact:
    infra_ssh_key: "{{ vmc_ssh_key_path }}"
    env_authorized_key: >-
      {{ vmc_ssh_pub_key_path | basename | splitext | first }}
