---
- name: Debug VMC Instances fact
  debug:
    var: r_vmc_instances
    verbosity: 2

# Find the bastion
- name: Find the bastion in this batch of hosts
  loop: "{{ r_vmc_instances | list }}"
  set_fact:
    local_bastion: "{{ item.instance.hw_name }}"
  when:
    - item.instance.customvalues.AnsibleGroup|default("") == "bastions"
  ignore_errors: true

- debug: var=local_bastion

- name: Debug OpenShift CNV Instances fact
  debug:
    var: r_vmc_instances
    verbosity: 2


- name: Create inventory (add_host)
  loop: "{{ r_vmc_instances | list }}"
  add_host:
    name: "{{ item.instance.hw_name }}"
    shortname: "{{ item.instance.hw_name }}"
    ansible_ssh_host: "{{ item.instance.hw_name }}"
    private_ip_address: "{{ item.instance.ipv4 }}"
    public_ip_address: "{{ publicips | json_query(\"[?name=='{{item.instance.hw_name }}'].ip\") | default('') }}"
    groups: "{{ item.instance.customvalues.AnsibleGroup | default(omit) }}"
    bastion: "{{ local_bastion | default('') }}"
    isolated: "{{ item.instance.customvalues.isolated | default(False) }}"



